name = "No linguistic content"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.zxx"

[windows]
system_product_code = "{F74EF165-11B3-4E5C-A524-D4346F39FB9F}_is1"
legacy_product_codes = [
    { value = "17B62C96-9A55-4292-9957-AEC1D42AB325", kind = "nsis" },
    { value = "374C94A1-D8EA-4289-9016-DB93D7C5679A", kind = "nsis" }
]
