template = "https://github.com/giellalt/template-lang-und"
rev_id = 312
template_sha = "aaa43738ed413bb95e9bd39f5489b35bab88cc4b"

[replacements]
__GLOTTOLOG_ID__ = "Undefined"
__REPO__ = "lang-zxx"
__UND2C__ = "zxx"
__UNDEFINED__ = "No linguistic content"
__UND__ = "zxx"
