template = "https://github.com/giellalt/template-lang-und"
rev_id = 294
template_sha = "a620868b33dee503846060f7bd6c6e88f3c1f6d1"

[replacements]
__GLOTTOLOG_ID__ = "Undefined"
__REPO__ = "lang-zxx"
__UND2C__ = "zxx"
__UNDEFINED__ = "No linguistic content"
__UND__ = "zxx"
