[package]
name = "zxx"
human_name = "No linguistic content"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.zxx]
filename = "zxx-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-zxx"
platform = "windows"
uuid = "17B62C96-9A55-4292-9957-AEC1D42AB325"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.zxx"
package = "speller-zxx"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-zxx-mso"
platform = "windows"
uuid = "374C94A1-D8EA-4289-9016-DB93D7C5679A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-zxx"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
