theme: jekyll-theme-giellalt
title: NLP Grammar with no linguistic content
description: Finite state and Constraint Grammar based testing bed. Asume nothing works!

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
