name: Build in-code documentation
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: giellalt/giella-core
          path: giella-core
      - uses: actions/checkout@v2
        with:
          repository: giellalt/giella-shared
          path: giella-shared
      - uses: actions/checkout@v2
        with:
          path: lang
      - name: Install dev dependencies
        uses: divvun/actions/lang/install-deps@master
        with:
          sudo: true
      - name: Build giella-core/giella-shared
        uses: divvun/actions/lang/build@master
        with:
          spellers: false
          fst: hfst

# Mermaid processing starts here:
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(find lang/docs -name '*.md' | xargs)"

      - name: md files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'lang/docs/.resources'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: "svg"

      - name: show changes
        run: |
          cd lang && git status ; ls -l docs/.resources

      - name: list resource dir
        run: |
          cd lang/docs && ls -laR

      - name: cat Test file
        run: |
          cd lang/docs && cat Test.md

# Mermaid processing ends here - how to get them into the deployment?

      - name: deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lang/docs/
          enable_jekyll: true
