name: Send Zulip message
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout files
        with:
          fetch-depth: '2'
          persist-credentials: 'true'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Send a stream message
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: "github-bot@giella.zulipchat.com"
          organization-url: "https://giella.zulipchat.com"
          to: "zxx"
          type: "stream"
          topic: "Castle"
          content: "I come not, friends, to steal away your hearts. The changed files are these: ${{steps.changed-files.outputs.all_modified_files}}"
