name: Send Zulip message
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout files
        with:
          fetch-depth: '2'
          persist-credentials: 'true'
#      - uses: actions/github-script@v6
#        with:
#          script: |
#            const commits = ${{ toJSON(github.event.commits) }}
#            for (const commit of commits) {
#              console.log(commit);
#            }
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Logging
        id: log
        run: |
          echo "files=$(echo ${{steps.changed-files.outputs.all_modified_files}} | tr ' ' '\n' | sed 's/^/- /g' )" >> $GITHUB_OUTPUT
      - name: Send a stream message
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: "github-bot@giella.zulipchat.com"
          organization-url: "https://giella.zulipchat.com"
          to: "zxx"
          type: "stream"
          topic: "Castle"
          content: "Changed files:\n- ${{steps.changed-files.outputs.all_modified_files}} \n\n ${{steps.log.outputs.files}}"
